DROP TABLE `comment`;
DROP TABLE `media_info_hashtag`;
DROP TABLE `hashtag`;
DROP TABLE `track`;
DROP TABLE `media`;
DROP TABLE `channel`;
DROP TABLE `address`;
DROP TABLE `contact`;
DROP TABLE `user`;
